apiVersion: v1
kind: Secret
metadata:
  name: {{ template "prometheus-pve-exporter.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "prometheus-pve-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "prometheus-pve-exporter.chart" . }}
type: Opaque
stringData:
  pve.yml: |-
    default:
      user: {{ .Values.pve.user }}
      password: {{ .Values.pve.password }}
      verify_ssl: {{ .Values.pve.verify_ssl }}
